### ISSUE TITLE
Bad code

### ISSUE THREAD

**Issue by ghost** [Kacper1263/Tracky#7]
Bad code

**Comment by ghost** [comment]
please fix

**Comment by Kacper1263** [comment]
this is an open source project, you can write it better and do PR 😉

**Comment by ghost** [comment]
how to learn dart

**Comment by ghost** [comment]
kacper help

**Comment by ak47russian** [comment]
Idk what happend here, but i had similar issue. I realized that i need to recreate config file based on code, it is annoying. But project is nice :D Perfect for learning

**Comment by ak47russian** [comment]
ugabuga
